apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDenyHostNetPrivileged
metadata:
  name: deny-hostnet-privileged
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment","StatefulSet","DaemonSet"]
