# database deployment + service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-bank-db
  labels:
    app: vuln-bank-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-bank-db
  template:
    metadata:
      labels:
        app: vuln-bank-db
    # BAD: Database running as root
    spec:
      containers:
        - name: postgres
          image: postgres:13
      # No securityContext = runs as root (UID 0)
          env:
            - name: POSTGRES_DB
              value: "vulnerable_bank"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}

---
# Database Service
apiVersion: v1
kind: Service
metadata:
  name: vuln-bank-db
spec:
  selector:
    app: vuln-bank-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
