name: Gatekeeper CI Policy Validation
on:
  push:
  pull_request:
  workflow_dispatch:
#   push:
#     paths:
#       - 'k8s-policies/gatekeeper/**'
#       - 'k8s/**'
#   pull_request:
#     paths:
#       - 'k8s-policies/gatekeeper/**'
#       - 'k8s/**'

jobs:
  gatekeeper-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Gator CLI
        run: |
          latest=$(curl -s https://api.github.com/repos/open-policy-agent/gatekeeper/releases/latest | grep browser_download_url | grep gator-linux-amd64 | cut -d '"' -f 4)
          curl -L -o gator "$latest"
          chmod +x gator
          sudo mv gator /usr/local/bin/

      - name: Run Gator tests
        run: |
          # run verification against Gatekeeper templates + constraints + sample resources
          gator test k8s-policies/gatekeeper || (echo "Gatekeeper policy failures" && exit 1)