name: Gatekeeper CI Policy Validation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  gatekeeper-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Gator CLI
        run: |
          set -e
          
          # Get the latest release info
          latest_url=$(curl -s https://api.github.com/repos/open-policy-agent/gatekeeper/releases/latest \
            | jq -r '.assets[] | select(.name | contains("gator") and contains("linux") and contains("amd64") and endswith(".tar.gz")) | .browser_download_url')
          
          echo "Downloading Gator from: $latest_url"
          
          if [ -z "$latest_url" ]; then
            echo "ERROR: Could not find Gator download URL"
            exit 1
          fi
          
          # Download and extract
          curl -L -o gator.tar.gz "$latest_url"
          tar -xzf gator.tar.gz
          
          # Move to bin and make executable
          sudo mv gator /usr/local/bin/
          sudo chmod +x /usr/local/bin/gator
          
          # Verify installation
          gator version
        # run: |
        #   latest=$(curl -s https://api.github.com/repos/open-policy-agent/gatekeeper/releases/latest \
        #     | jq -r '.assets[] | select(.name | test("gator.*linux.*amd64")) | .browser_download_url')
        #   echo "Downloading Gator from: $latest"
        #   if [ -z "$latest" ]; then
        #     echo "ERROR: Could not find a matching Gator download URL"
        #     exit 1
        #   fi
        #   curl -L -o gator "$latest"
        #   chmod +x gator
        #   sudo mv gator /usr/local/bin/

      - name: Validate directory structure
        run: |
          if [ ! -d "k8s-policies/gatekeeper" ]; then
            echo "ERROR: k8s-policies/gatekeeper directory not found"
            echo "Current directory structure:"
            ls -R
            exit 1
          fi

      - name: Run Gator tests
        run: |
          set -e
          echo "Running Gatekeeper policy validation..."
          
          # Run gator test on the policies directory
          if gator test k8s-policies/gatekeeper; then
            echo "✅ All Gatekeeper policies passed validation"
          else
            echo "❌ Gatekeeper policy validation failed"
            exit 1
          fi

      - name: Verify constraints and templates
        run: |
          echo "Checking for constraint templates..."
          find k8s-policies/gatekeeper -name "*template*.yaml" -o -name "*constraint*.yaml"