name: Kyverno CI Policy Validation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  kyverno-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Kyverno CLI
        run: |
          set -e
          
          # Get the latest release info
          latest_url=$(curl -s https://api.github.com/repos/kyverno/kyverno/releases/latest \
            | jq -r '.assets[] | select(.name | contains("kyverno-cli") and contains("linux") and contains("x86_64") and endswith(".tar.gz")) | .browser_download_url')
          
          echo "Downloading Kyverno CLI from: $latest_url"
          
          if [ -z "$latest_url" ]; then
            echo "ERROR: Could not find Kyverno CLI download URL"
            exit 1
          fi
          
          # Download and extract
          curl -L -o kyverno.tar.gz "$latest_url"
          tar -xzf kyverno.tar.gz
          
          # Move to bin and make executable
          sudo mv kyverno /usr/local/bin/
          sudo chmod +x /usr/local/bin/kyverno
          
          # Verify installation 
            kyverno version

      - name: Validate directory structure
        run: |
          if [ ! -d "k8s-policies/kyverno" ]; then
            echo "ERROR: k8s-policies/kyverno directory not found"
            echo "Current directory structure:"
            ls -R
            exit 1
          fi
    #   - name: Validate Kyverno policies
        # run: |
        #   set -e
        #   echo "Running Kyverno policy validation..."
          
        #   # Apply policies in dry-run mode
        #   # -r: apply policies recursively
        #   if kyverno apply k8s-policies/kyverno --resource k8s --policy k8s-policies/kyverno; then
        #     echo "All Kyverno policies passed validation"
        #   else
        #     echo "Kyverno policy validation failed"
        #     exit 1
        #   fi

      - name: Test Compliant Resources
        run: |
            set -e
            echo "Testing COMPLIANT manifests..."
            echo ""
            
            # Test the fixed deployment
            echo "Testing: deployment-kyverno-fixed.yaml"
            if kyverno apply k8s-policies/kyverno --resource k8s/compliant/deployment-kyverno-fixed.yaml; then
                echo "Fixed deployment passed validation"
            else
                echo "Fixed deployment failed (should not happen!)"
                exit 1
            fi
            
            echo ""
            echo "Testing: Other valid resources"
            kyverno apply k8s-policies/kyverno \
                --resource k8s/compliant/db-kyverno-fixed.yaml \
                --resource k8s/service.yaml
            
            echo ""
            echo "All compliant resources passed policy validation"
            
      - name: Test Non-Compliant Resources (Expected to Fail)
        run: |
          set -e
          echo ""
          echo "Testing NON-COMPLIANT resources..."
          echo "-------------------------------------------"
          echo "These SHOULD fail - that proves policies work!"
          echo "--------------------------------------------"
          echo ""
          
          # Test the non-compliant deployment
          echo "Testing: deployment.yaml (original/non-compliant)"
          if kyverno apply k8s-policies/kyverno --resource k8s/deployment.yaml; then
            echo "WARNING: Non-compliant resource was NOT blocked!"
            echo "Policies may not be working correctly."
            exit 1
          else
            echo "Non-compliant resource correctly blocked by policy"
          fi
          
          echo ""

          # Test the non-compliant database resource
          echo "Testing: db.yaml"
          if kyverno apply k8s-policies/kyverno --resource k8s/db.yaml; then
            echo "WARNING: Non-compliant DB resource was NOT blocked!"
            echo "Policies may not be working correctly."
            exit 1
          else
            echo "Non-compliant DB resource correctly blocked by policy"
          fi
          echo ""
          echo "Policy enforcement verified successfully!"

    #   - name: Test Kyverno policies (only if we have a test directory, for future-proof )
    #     run: |
    #       if [ -d "k8s-policies/kyverno/test" ]; then
    #         echo "Running Kyverno tests..."
    #         kyverno test k8s-policies/kyverno
    #       else
    #         echo "No test directory found, skipping kyverno test command"
    #       fi

      - name: List Kyverno policies
        run: |
          echo "Kyverno policies found:"
          find k8s-policies/kyverno -name "*.yaml" -o -name "*.yml"
