name: Kyverno CI Policy Validation
on:
  push:
  pull_request:
  workflow_dispatch:

#   push:
#     paths:
#       - 'k8s/**'
#       - 'k8s-policies/kyverno/**'
#   pull_request:
#     paths:
#       - 'k8s/**'
#       - 'k8s-policies/kyverno/**'

jobs:
  kyverno-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run kyverno apply (dry-run) using kyverno CLI
        run: |
          latest=$(curl -s https://api.github.com/repos/kyverno/kyverno/releases/latest | grep browser_download_url | grep linux_amd64 | grep cli | cut -d '"' -f 4)
          curl -L -o kyverno "$latest"
          chmod +x kyverno
          sudo mv kyverno /usr/local/bin/

      - name: Validate Kyverno policies (dry-run)
        run: |
          kyverno apply k8s-policies/kyverno -r -x
