name: Kyverno CI Policy Validation
on:
  push:
  pull_request:
  workflow_dispatch:

#   push:
#     paths:
#       - 'k8s/**'
#       - 'k8s-policies/kyverno/**'
#   pull_request:
#     paths:
#       - 'k8s/**'
#       - 'k8s-policies/kyverno/**'

jobs:
  kyverno-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run kyverno apply (dry-run) using kyverno CLI
        run: |
          set -e
          latest=$(curl -s https://api.github.com/repos/kyverno/kyverno/releases/latest \
            | jq -r '.assets[] | select(.name | test("kyverno-cli_.*linux_x86_64\\.tar\\.gz$")) | .browser_download_url' | head -n 1)
          echo "Downloading Kyverno CLI from: $latest"
          if [ -z "$latest" ]; then
            echo "ERROR: Could not find a matching Kyverno CLI download URL"
            exit 1
          fi

          curl -L -o kyverno.tar.gz "$latest"
          tar -xzf kyverno.tar.gz
          sudo mv kyverno /usr/local/bin/
          chmod +x /usr/local/bin/kyverno
          kyverno version  
      # run: |
        #   latest=$(curl -s https://api.github.com/repos/kyverno/kyverno/releases/latest \
        #     | jq -r '.assets[] | select(.name | test("kyverno-cli.*linux.*(amd64|x86_64)")) | .browser_download_url')
        #   echo "Downloading Kyverno CLI from: $latest"
        #   if [ -z "$latest" ]; then
        #     echo "ERROR: Could not find a matching Kyverno CLI download URL"
        #     exit 1
        #   fi
        #   curl -L -o kyverno "$latest"
        #   chmod +x kyverno
        #   sudo mv kyverno /usr/local/bin/

      - name: Validate Kyverno policies (dry-run)
        run: |
          kyverno apply k8s-policies/kyverno -r -x
